__projectname__ = 'continuous_delivery'
__version__ = '1.0.3'
__release__ = __version__
__authors__ = 'Tyghe Vallard'
__authoremails__ = 'vallardt@gmail.com'
__description__ = 'Travis + Github continuous delivery testing'
__license__ = ''
__keywords__ = ''
__url__ = 'https://github.com/necrolyte2/' + __projectname__
